version: '3'
services:
  app:
    container_name: golang_container
    build: .
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
    volumes:
      - .:/app
    depends_on:
      database:
        condition: service_healthy
    networks:
      - network1
  database:
    container_name: database
    image: 'postgres:latest'
    ports:
      - "1111:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - network1

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 11s
      timeout: 6s
      retries: 6
networks:
  network1: